USE Master
GO

SELECT * FROM VRAAG
SELECT * FROM VRAAGONDERDEEL
SELECT * FROM ANTWOORD

SELECT MAX(VRAAGONDERDEELNUMMER)
FROM VRAAGONDERDEEL
GROUP BY VRAAGONDERDEELNUMMER, VRAAG_ID
HAVING VRAAG_ID = (SELECT VRAAG_ID
					FROM VRAAG
					WHERE VRAAG_NAAM = 'Testvraag6')

SELECT COUNT(*) FROM VRAAGONDERDEEL INNER JOIN VRAAG ON VRAAGONDERDEEL.VRAAG_ID = VRAAG.VRAAG_ID WHERE VRAAG_NAAM = 'Testvraag6'

EXEC dbo.usp_Vraagonderdeel_Insert @VRAAG_NAAM = 'Test2', @VRAAGONDERDEELNUMMER = '3', @VRAAGONDERDEEL = 'Dit is een Testvraag?3', @VRAAGSOORT = 'G'

