USE BANG
GO

CREATE LOGIN  [BANG_DBA]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [BANG_DBA] FOR LOGIN [BANG_DBA];
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [BANG_DBA];
GO

CREATE LOGIN  [bang_organisator]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_beheerder]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_quizmaker]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_quizmaster]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_top100medewerker]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_stemmer]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN  [bang_deelnemer]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
