USE BANG
GO

CREATE LOGIN  [BANG_DBA]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [BANG_DBA] FOR LOGIN [BANG_DBA];
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [BANG_DBA];
GO

CREATE LOGIN  [BANG_FRONT_END]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [BANG_FRONT_END] FOR LOGIN [BANG_FRONT_END];
GO

ALTER ROLE db_owner ADD MEMBER [BANG_FRONT_END];
GO
