USE BANG
GO

CREATE LOGIN  [BANG_DBA]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [BANG_DBA] FOR LOGIN [BANG_DBA];
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [BANG_DBA];
GO

CREATE LOGIN  [BANG_FRONT_END]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [BANG_FRONT_END] FOR LOGIN [BANG_FRONT_END];
GO

ALTER ROLE db_owner ADD MEMBER [BANG_FRONT_END];
GO

CREATE LOGIN  [bang_organisator]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_organisator] FOR LOGIN [bang_organisator];
GO

ALTER ROLE [bang_organisator_role] ADD MEMBER [bang_organisator];
GO

CREATE LOGIN  [bang_beheerder]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_beheerder] FOR LOGIN [bang_beheerder];
GO

ALTER ROLE db_owner ADD MEMBER [bang_beheerder];
GO

CREATE LOGIN  [bang_quizmaker]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_quizmaker] FOR LOGIN [bang_quizmaker];
GO

ALTER ROLE [bang_quizmaker_role] ADD MEMBER [bang_quizmaker];
GO

CREATE LOGIN  [bang_quizmaster]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_quizmaster] FOR LOGIN [bang_quizmaster];
GO

ALTER ROLE [bang_quizmaster_role] ADD MEMBER [bang_quizmaster];
GO

CREATE LOGIN  [bang_top100medewerker]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_top100medewerker] FOR LOGIN [bang_top100medewerker];
GO

ALTER ROLE [bang_top100medewerker_role] ADD MEMBER [bang_top100medewerker];
GO

CREATE LOGIN  [bang_stemmer]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_stemmer] FOR LOGIN [bang_stemmer];
GO

ALTER ROLE [bang_stemmer_role] ADD MEMBER [bang_stemmer];
GO

CREATE LOGIN  [bang_deelnemer]
WITH PASSWORD= 'L72)zdTQr&v$5n+M', 	
DEFAULT_DATABASE=[BANG], DEFAULT_LANGUAGE=[us_english], 	
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [bang_deelnemer] FOR LOGIN [bang_deelnemer];
GO

ALTER ROLE [bang_deelnemer_role] ADD MEMBER [bang_deelnemer];
GO